name: Deploy Go App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.2'

    - name: Build
      run: |
        go build -o cadeteria cmd/main.go
    - name: Install binary and setup systemd service
      run: |
        echo "@Cadeteria2024712pymbu" | sudo -S sh -c 'echo "[Unit]
        Description=backeng cadeteria
        After=network.target
    
        [Service]
        Type=simple
        WorkingDirectory=/home/developer/api.cadeteria-mvd.com/actions-runner/_work/CMVD-API/CMVD-API
        ExecStart=/home/developer/api.cadeteria-mvd.com/actions-runner/_work/CMVD-API/CMVD-API/cadeteria
        Environment=APP_ENV=production
        [Install]
        WantedBy=multi-user.target" > /etc/systemd/system/cadeteria.service'
        sudo systemctl stop cadeteria.service || true
        sudo systemctl daemon-reload
        sudo systemctl enable cadeteria.service
        sudo systemctl start cadeteria.service
